/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './public/index.html',
    './src/**/*.{js,jsx,ts,tsx}',
    './build/index.html',
  ],
  safelist: [
    'dark',
    'bg-base-100',
    'bg-base-200',
    'dark:bg-neutral-800',
    'dark:text-neutral-100',
    'dark:text-neutral-200',
    'dark:text-neutral-300',
    'dark:border-neutral-500',
    'dark:border-neutral-600',
    'dark:placeholder-neutral-300',
    'dark:bg-neutral-600',
    'dark:bg-neutral-700',
    'dark:hover:bg-neutral-500',
    'dark:hover:bg-neutral-600',
    'dark:hover:text-neutral-100',
    'dark:hover:text-neutral-200',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'Noto Sans', 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'],
      },
      colors: {
        brand: {
          DEFAULT: '#6366f1',
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
        },
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        quantumlight: {
          primary: '#6366f1',
          'primary-focus': '#4f46e5',
          'primary-content': '#ffffff',
          secondary: '#22d3ee',
          'secondary-focus': '#0891b2',
          'secondary-content': '#ffffff',
          accent: '#f472b6',
          'accent-focus': '#ec4899',
          'accent-content': '#ffffff',
          neutral: '#374151',
          'neutral-focus': '#1f2937',
          'neutral-content': '#ffffff',
          'base-100': '#ffffff',
          'base-200': '#f9fafb',
          'base-300': '#f3f4f6',
          'base-content': '#1f2937',
          info: '#3b82f6',
          'info-content': '#ffffff',
          success: '#10b981',
          'success-content': '#ffffff',
          warning: '#f59e0b',
          'warning-content': '#ffffff',
          error: '#ef4444',
          'error-content': '#ffffff',
        },
      },
      {
        quantumdark: {
          primary: '#818cf8',
          'primary-focus': '#6366f1',
          'primary-content': '#000000',
          secondary: '#34d399',
          'secondary-focus': '#10b981',
          'secondary-content': '#000000',
          accent: '#fbbf24',
          'accent-focus': '#f59e0b',
          'accent-content': '#000000',
          neutral: '#374151',
          'neutral-focus': '#1f2937',
          'neutral-content': '#d1d5db',
          'base-100': '#1f2937',
          'base-200': '#374151',
          'base-300': '#4b5563',
          'base-content': '#f9fafb',
          info: '#60a5fa',
          'info-content': '#000000',
          success: '#34d399',
          'success-content': '#000000',
          warning: '#fbbf24',
          'warning-content': '#000000',
          error: '#f87171',
          'error-content': '#000000',
        },
      },
    ],
  },
};


