app = "quantumfieldkit"
primary_region = "arn"
kill_signal = "SIGINT"
kill_timeout = "10s"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  FLASK_ENV = "production"
  PYTHONPATH = "/app"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 2
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

  # Health check configuration
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/api/plugins"
    timeout = "5s"
    headers = {}

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

# Optional: Add secrets for sensitive configuration
# [secrets]
#   SECRET_KEY = "your-secret-key"